FROM node:22 AS base
WORKDIR /app
COPY package*.json ./
COPY . .
RUN npm install
RUN npx prisma generate
CMD [ "npm", "run", "dev" ]

FROM base AS builder
COPY . .
RUN npm run build

FROM base AS production
COPY --from=builder /app/.next ./.next/
COPY --from=builder /app/node_modules ./node_modules/
COPY --from=builder /app/public ./public/
COPY --from=builder /app/prisma ./prisma/
COPY package*.json ./
CMD [ "npm", "start" ]
