name: Deploy to vm

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/my-image

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.yml
          push: true
          tags: dillax/muzer_app:${{ github.sha }}

      - name: Deploy to the Vm
        run: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
            chmod 600 ~/ssh_key
            ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.61.186.145 << EOF
              set -e
              IMAGE=dillax/muzer_app:${GITHUB_SHA}
              sudo docker stop muzer_app || true
              sudo docker rm muzer_app || true
              
              sudo docker run --name muzer_app -d -p 3000:3000 \$IMAGE
            EOF